### ISSUE TITLE
购买

### ISSUE THREAD

**Issue by labspc** [lizer/jekyll-blog#11]
请问这个 GitHub 账号您转手吗？看起来，您似乎不太使用这个账号，我很想接手这个账号。

**Comment by lizer** [comment]
> 请问这个 GitHub 账号您转手吗？看起来，您似乎不太使用这个账号，我很想接手这个账号。

您好，为什么想接手这个账号呢？

**Comment by labspc** [comment]
hhh哈，就是因为这个账号比我的账号注册的时间早，美滋滋的。其实，就这个原因吧，看着好看，也没有其他原因。简单说就是：哇，你接触 GitHub 这么早。hhh哈，我就可以得瑟一下。

**Comment by labspc** [comment]
您有转手的意愿吗？只是觉得这个号注册时间比我的久一点儿，看着好看。如果您可以把账号转手给我的话，username 我肯定是会更改的（重置账号）。因为是我个人，所以也不牵扯什么其他利益。

**Comment by lizer** [comment]
那您愿意出价多少呢

**Comment by labspc** [comment]
我之前没买过账号。只买过域名23333，其实我也没钱，不知道出多少。
这个账号您愿意多钱出呢？不知道 **＜100￥** ，几十块钱您愿意出吗？

**Comment by labspc** [comment]
几十确实感觉不多，但是不开学没有生活费啊23333。之前买了域名和阿里的机机，现在真就剩几十r了。👀

**Comment by lizer** [comment]
本来想送你的。 刚刚回忆了下，这个账号已经关联了好多东西，比如dashing.io
和知乎上的引用。blog虽然不更新了，但每个月还有几百个外链来的流量。还是算了吧。不好意思！

**Comment by labspc** [comment]
嗯嗯。我也是看帖的时候，看到的这个账号。

**Comment by labspc** [comment]
不过，还是很谢谢了2333

**Comment by labspc** [comment]
您应该有大号吧，我可以 Follow 一下您吗

**Comment by lizer** [comment]
我已经不太用github了，现在公司对安全比较敏感，公共代码仓库我就不用了。

**Comment by labspc** [comment]
啊！dalao 可以加一下你微信吗？😁

**Comment by pyfn2030** [comment]
啊！dalao 可以加一下你微信吗？😁

**Comment by pyfn2030** [comment]
啊！dalao 可以加一下你微信吗？😁

**Comment by labspc** [comment]
不好意思，刚刚重复发送了。

**Comment by lizer** [comment]
你发微信号到darwin.ncu at gmail.com吧 我加你
